@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package pw.tales.cofdsystem.mod.server.modules.action_roll;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;