@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package pw.tales.cofdsystem.mod.server.modules.go_relation_entity.events;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;