@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package pw.tales.cofdsystem.mod.server.modules.notification;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;