@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package pw.tales.cofdsystem.mod.client.projection;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;