@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package pw.tales.cofdsystem.mod.server.modules.go_relation_entity.capabilities.binding;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;