name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        run: ./gradlew build
      - name: Upload binaries to release
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./libs/tales_system-$RELEASE_VERSION.jar
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
